### ISSUE TITLE
Missing the information in "About" field

### ISSUE THREAD

**Issue by VietTran0302** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure.ko-kr#126]
Missing the information in "About" field.

Missing the Link to "Github Pages"

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by VietTran0302** [comment]
Hi,

Please refer the below screenshot.
![image](https://user-images.githubusercontent.com/64255878/168540425-fca39a06-53b6-46a6-8401-49e027c4d47f.png)

**Comment by stonezy123** [comment]
not loclization issue

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/180975113-8793a636-d21b-4753-91f7-93ddf680e196.png)
add it
