### ISSUE TITLE
Student + LAK Instructions documents have a Note with leading spaces, leading to undesired rendering.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-800-Administering-Windows-Server-Hybrid-Core-Infrastructure.ko-kr#127]
This line, in the starting section of all student + LAK lab instructions appears to have ~16 additional/unneeded spaces:

                **참고:** **[대화형 랩 시뮬레이션](https://mslabs.cloudguides.com/guides/AZ-800%20Lab%20Simulation%20-%20Implementing%20identity%20services%20and%20Group%20Policy)** 을 사용하여 이 랩을 원하는 속도로 클릭할 수 있습니다. 대화형 시뮬레이션과 호스트된 랩 간에 약간의 차이가 있을 수 있지만 보여주는 핵심 개념과 아이디어는 동일합니다. 

This leads to undesirable display in both Github and ALH rendering.

If one removes the leading spaces, it displays as expected:

![image](https://user-images.githubusercontent.com/49700217/228994421-94486354-ed44-4b43-815f-5e73f350d7f1.png)

**Comment by chriscarty00** [comment]
[Locfiles](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO1dXTDwvUVI%2bPFFSIElkPSIyIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEFzc2V0IElEO1N0YXJ0cyBXaXRoO0xBQl9BSzwvUVI%2bPFFSIElkPSIzIiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtLb3JlYW4gKEtvcmVhKTwvUVI%2bPFFSIElkPSI0IiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IEFzc2V0IElEO0NvbnRhaW5zOy5tZDwvUVI%2bPFFSIElkPSI1IiBDUElEPSIwIj5hbmQ7Q3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgR3JvdXA7Q29udGFpbnM7QVotODAwPC9RUj48UVIgSWQ9IjYiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7Q29udGFpbnM7NTAzMzQ8L1FSPjwvUVQ%2bPFJHPjxHQz5OVUxMPC9HQz48L1JHPjwvVlBRPg%3d%3d) to update
